<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8">
    <title>{{ $title }}</title>
    <style>
        body { font-family: sans-serif; font-size: 11px; color: #1a1a1a; margin: 0; padding: 20px; }
        h2 { font-size: 16px; margin: 0 0 4px 0; }
        .meta { color: #666; font-size: 10px; margin-bottom: 16px; }
        table { width: 100%; border-collapse: collapse; }
        th { background: #f3f4f6; font-weight: 600; text-align: left; padding: 8px 10px; border: 1px solid #d1d5db; font-size: 10px; text-transform: uppercase; letter-spacing: 0.5px; color: #374151; }
        td { padding: 6px 10px; border: 1px solid #e5e7eb; vertical-align: top; }
        tr:nth-child(even) td { background: #f9fafb; }
        .footer { margin-top: 16px; font-size: 9px; color: #9ca3af; text-align: right; }
    </style>
</head>
<body>
    <h2>{{ $title }}</h2>
    <div class="meta">{{ now()->format('d M Y, H:i') }} &mdash; {{ count($rows) }} rows</div>

    <table>
        <thead>
            <tr>
                @foreach($headers as $header)
                    <th>{{ $header }}</th>
                @endforeach
            </tr>
        </thead>
        <tbody>
            @forelse($rows as $row)
                <tr>
                    @foreach($row as $cell)
                        <td>{{ $cell }}</td>
                    @endforeach
                </tr>
            @empty
                <tr>
                    <td colspan="{{ count($headers) }}" style="text-align:center;color:#9ca3af;padding:20px;">No data</td>
                </tr>
            @endforelse
        </tbody>
    </table>

    <div class="footer">Generated by MrCatz DataTable</div>
</body>
</html>
